from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.api.deps import get_current_user
from app.models.user import User
from app.schemas.slack import SlackConnectResponse, SlackStatusResponse, SlackToggleRequest
from app.services.auth_service import create_access_token, decode_access_token
from app.services import slack_service

router = APIRouter(prefix="/slack", tags=["Slack"])


@router.get("/connect", response_model=SlackConnectResponse)
def connect_slack(current_user: User = Depends(get_current_user)):
    """
    Returns the Slack authorization URL for the logged-in user. The
    frontend navigates the browser to this URL directly (window.location),
    rather than this endpoint redirecting itself, since it needs the
    user's JWT to identify who is connecting — and a raw browser
    navigation can't carry an Authorization header.
    """
    state = create_access_token({"sub": current_user.email, "purpose": "slack_oauth"})
    try:
        url = slack_service.build_authorize_url(state)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    return SlackConnectResponse(authorize_url=url)


@router.get("/callback")
def slack_callback(code: str = Query(...), state: str = Query(...), db: Session = Depends(get_db)):
    """
    Slack redirects the user's browser here after they approve the app.
    No user JWT is available on this request — instead, the `state`
    param (a signed token generated by /connect) is decoded to identify
    which user initiated this flow.
    """
    payload = decode_access_token(state)
    if payload is None or payload.get("purpose") != "slack_oauth":
        raise HTTPException(status_code=400, detail="Invalid or expired Slack OAuth state.")

    email = payload.get("sub")
    user = db.query(User).filter(User.email == email).first()
    if user is None:
        raise HTTPException(status_code=400, detail="User not found for this Slack OAuth session.")

    try:
        token_data = slack_service.exchange_code_for_token(code)
        slack_service.save_slack_connection(db, user, token_data)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))

    return RedirectResponse(url=f"{settings.frontend_url}/settings?slack=connected")


@router.get("/status", response_model=SlackStatusResponse)
def slack_status(current_user: User = Depends(get_current_user)):
    return SlackStatusResponse(
        connected=current_user.slack_connected,
        enabled=current_user.slack_enabled,
        workspace_name=current_user.slack_workspace_name,
    )


@router.post("/disconnect", response_model=SlackStatusResponse)
def disconnect_slack_route(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    slack_service.disconnect_slack(db, current_user)
    return SlackStatusResponse(connected=False, enabled=False, workspace_name=None)


@router.post("/toggle", response_model=SlackStatusResponse)
def toggle_slack(
    request: SlackToggleRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    if not current_user.slack_connected and request.enabled:
        raise HTTPException(status_code=400, detail="Connect Slack before enabling notifications.")

    slack_service.set_slack_enabled(db, current_user, request.enabled)
    return SlackStatusResponse(
        connected=current_user.slack_connected,
        enabled=current_user.slack_enabled,
        workspace_name=current_user.slack_workspace_name,
    )